#ece3 or ece4:
dataset_type: #specify model version: ece3 or ece4
kernels:
    era5:
      path_input: "/path/to/kernels/Huang_ERA5/"
      path_output: "/path/to/kernels/output/"
      filename_template: "ERA5_kernel_{}_TOA.nc"
    huang:
      path_input: "/path/to/kernels/Huang/toa/"
      path_output: "/path/to/kernels/output/"
      filename_template: "RRTMG_{}_toa_{}_highR.nc"

file_paths:
   reference_dataset: "/path/to/reference_data/"
   reference_dataset_pl: "/path/to/reference_data/level_pressure"
   experiment_dataset: "/path/to/experiment_data/"
   experiment_dataset2: "" #if you need a second experiment dataset, specify it here 
   experiment_dataset_pl: "/path/to/experiment_data/level_pressure"
   pressure_data: "" #to specify if you have ps values in a different file and not in an array
   output: "/path/to/output/"

use_climatology: True
use_ds_climatology: True
use_atm_mask: True
time_range: #this is the time range for the reference dataset 
   start: ""
   end: ""
time_range_exp: #this is the time range for the experiment dataset, give it empty if you want to use the same as the reference dataset
   start: ""
   end: ""
time_chunk: 12